-- phpMyAdmin SQL Dump
-- Database: `ubuntutrade`
-- UbuntuTrade C2C platform schema


-- --------------------------------------------------------
-- Table: `role` (RBAC)
-- --------------------------------------------------------
CREATE TABLE `role` (
  `role_id` int(11) NOT NULL AUTO_INCREMENT,
  `role_name` varchar(50) NOT NULL,
  `permissions` text DEFAULT NULL,
  PRIMARY KEY (`role_id`)
);

-- --------------------------------------------------------
-- Table: `user`
-- --------------------------------------------------------
CREATE TABLE `user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(100) NOT NULL,
  `phone` varchar(15) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `is_verified_seller` tinyint(1) DEFAULT 0,
  `id_verified` tinyint(1) DEFAULT 0,
  `bank_verified` tinyint(1) DEFAULT 0,
  `role_id` int(11) DEFAULT 2,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email` (`email`),
  FOREIGN KEY (`role_id`) REFERENCES `role` (`role_id`) ON DELETE SET NULL
);

-- --------------------------------------------------------
-- Table: `listing`
-- --------------------------------------------------------
CREATE TABLE `listing` (
  `listing_id` int(11) NOT NULL AUTO_INCREMENT,
  `seller_id` int(11) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `category` varchar(50) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `status` enum('active','sold','inactive') DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`listing_id`),
  FOREIGN KEY (`seller_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE
);

-- --------------------------------------------------------
-- Table: `orders`
-- --------------------------------------------------------
CREATE TABLE `orders` (
  `order_id` int(11) NOT NULL AUTO_INCREMENT,
  `buyer_id` int(11) NOT NULL,
  `listing_id` int(11) NOT NULL,
  `total_amount` decimal(10,2) NOT NULL,
  `order_status` enum('pending','paid','shipped','delivered','cancelled') DEFAULT 'pending',
  `payment_status` enum('unpaid','paid','escrow_held','released') DEFAULT 'unpaid',
  `delivery_status` enum('not_shipped','shipped','delivered') DEFAULT 'not_shipped',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  FOREIGN KEY (`buyer_id`) REFERENCES `user` (`user_id`),
  FOREIGN KEY (`listing_id`) REFERENCES `listing` (`listing_id`)
);

-- --------------------------------------------------------
-- Table: `payment`
-- --------------------------------------------------------
CREATE TABLE `payment` (
  `payment_id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `gateway_txn_id` varchar(100) DEFAULT NULL,
  `escrow_released` tinyint(1) DEFAULT 0,
  `payment_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE
);

-- --------------------------------------------------------
-- Table: `review`
-- --------------------------------------------------------
CREATE TABLE `review` (
  `review_id` int(11) NOT NULL AUTO_INCREMENT,
  `reviewer_id` int(11) NOT NULL,
  `seller_id` int(11) NOT NULL,
  `rating` int(11) DEFAULT NULL CHECK (`rating` >= 1 and `rating` <= 5),
  `comment` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`),
  FOREIGN KEY (`reviewer_id`) REFERENCES `user` (`user_id`),
  FOREIGN KEY (`seller_id`) REFERENCES `user` (`user_id`)
);

-- --------------------------------------------------------
-- Insert default roles
-- --------------------------------------------------------
INSERT INTO `role` (`role_id`, `role_name`, `permissions`) VALUES
(1, 'Admin', 'full_access'),
(2, 'Buyer', 'view,buy,review'),
(3, 'Seller', 'list,manage_own_products,view_orders');

-- --------------------------------------------------------
-- Insert admin user (password = 'admin123')
-- hash generated by password_hash('admin123', PASSWORD_DEFAULT)
-- --------------------------------------------------------
INSERT INTO `user` (`user_id`, `email`, `phone`, `password_hash`, `full_name`, `role_id`, `is_verified_seller`, `id_verified`, `bank_verified`) VALUES
(1, 'admin@ubuntutrade.co.za', '0712345678', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'System Administrator', 1, 1, 1, 1);

-- --------------------------------------------------------
-- Insert a sample product (from admin user)
-- --------------------------------------------------------
INSERT INTO `listing` (`listing_id`, `seller_id`, `title`, `description`, `price`, `category`, `image_url`, `status`) VALUES
(1, 1, 'Handmade Beaded Necklace', 'Beautiful traditional beads, perfect gift', 150.00, 'Accessories', 'necklace.jpg', 'active');

-- --------------------------------------------------------
-- Optional: insert a demo buyer (password = 'buyer123')
-- --------------------------------------------------------
INSERT INTO `user` (`email`, `phone`, `password_hash`, `full_name`, `role_id`, `is_verified_seller`, `id_verified`, `bank_verified`) VALUES
('buyer@example.com', '0820001111', '$2y$10$e0MYzXyjpJS7Pd0RVvHwHevSJh0.kBq3CJqQqZx5g5s5g5s5g5s5', 'Demo Buyer', 2, 0, 0, 0);

-- --------------------------------------------------------
-- Insert a sample review
-- --------------------------------------------------------
INSERT INTO `review` (`reviewer_id`, `seller_id`, `rating`, `comment`) VALUES
(2, 1, 5, 'Beautiful necklace, fast delivery!');

-- --------------------------------------------------------
-- Optional: insert a sample order (for testing)
-- --------------------------------------------------------
INSERT INTO `orders` (`buyer_id`, `listing_id`, `total_amount`, `order_status`, `payment_status`) VALUES
(2, 1, 150.00, 'paid', 'escrow_held');

-- --------------------------------------------------------
-- Insert corresponding payment record
-- --------------------------------------------------------
INSERT INTO `payment` (`order_id`, `amount`, `gateway_txn_id`, `escrow_released`) VALUES
(1, 150.00, 'TEST_SIM_001', 0);


-- --------------------------------------------------------
-- Done
-- --------------------------------------------------------